// <auto-generated />
using Exam2V1._0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam2V1._0.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam2V1._0.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "A wire can be passed through the bolt head to prevent loosening.",
                            Name = "Socket Head Cap Screws",
                            Price = 18.25,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "20 meters of cable capable of high-frequency signal transmission in wide bandwidths.",
                            Name = "Fiber Optic Cables",
                            Price = 1100.1099999999999,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Ideal for switching equipment settings; connects to PCB.",
                            Name = "Dip Switch",
                            Price = 4.1500000000000004,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "265mm and 735g",
                            Name = "Insulated Torque Wrench",
                            Price = 386.27999999999997,
                            Quantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
